micronaut:
  application:
    name: tvshowsEngine
  server:
    cors:
      enabled: true
    port: 8082
endpoints:
  health:
    enabled: true
cassandra:
  default:
    clusterName: '"cassandra"'
    contactPoint: '"localhost"'
    port: 9042
    maxSchemaAgreementWaitSeconds: 20
    ssl: true
    consistencylevel: LOCAL_ONE
graphql:
  enabled: true
  path: /graphql
  graphiql:
    enabled: true
    version: 0.13.2
    path: /graphiql
    template-path: classpath:graphiql/index.html